# Name of your site (displayed in the header)
name: PORTABLE LINUX APPS

# XDG categories
# output: true = generate a page for each document in our collection
collections:
  categories:
    output: true

# Short bio or description (displayed in the header)
description: Welcome to the database of all AppImage packages and portable applications for GNU/Linux.

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Portable-Linux-Apps
  google_plus:
  instagram:
  linkedin:
  pinterest:
  rss: true
  twitter: 
  stackoverflow:
  youtube: # channel/<your_long_string> or user/<user-name>

# Your disqus shortname, entering this will enable commenting on posts
disqus: PortableLinuxApps

# Advanced config
permalink: /:title

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed 

# Use the following plug-ins

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag # https://help.github.com/articles/search-engine-optimization-for-github-pages/
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
