theme: jekyll-theme-primer
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

github:
  private: false
  repository_url: "https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io"
